# Generated by Django 3.2.11 on 2022-01-16 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='2f00cccfc6274ebdb8c9fac8a25851ab', max_length=33, verbose_name='UUID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 16, 15, 30, 59, 50597))),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
